<?xml version="1.0" ?>
<LIBRARIES>
  <LIBRARY>
    <NAME>AMP RF Power Library</NAME>
    <CATEGORY>DL</CATEGORY>
    <SUBLIBRARY>
      <NAME>AMP_BLF188XR_V1p02</NAME>
      <RECORD_FILES>AMP_BLF188XR_V1p02.rec</RECORD_FILES>
    </SUBLIBRARY>
  </LIBRARY>
</LIBRARIES>
